from datetime import timedelta

LIGHT_COUNT = 5

CHARGING_INTERVAL = timedelta(minutes=24)
ACTIVE_INTERVAL = timedelta(minutes=12)
RESET_DURATION = timedelta(minutes=5)

CHARGING_DURATION = CHARGING_INTERVAL * LIGHT_COUNT
ACTIVE_DURATION = ACTIVE_INTERVAL * LIGHT_COUNT
CYCLE_DURATION = CHARGING_DURATION + ACTIVE_DURATION + RESET_DURATION
